export const labelText = {
  funcionario: "Funcionario",
  sexo: "Sexo",
  correo: "Correo Electrónico",
  cedula: "Cedula",
  expedida: "Expedida en:",
  fechaNacimiento: "Fecha de nacimiento",
  lugarNacimiento: "Lugar de nacimiento",
  fechaIngreso: "Fecha Ingreso",
  tiempoServicio: "Tiempo de servicio",
  dependencia: "Dependencia",
  areafuncional: "Área funcional",
  cargo: "Cargo",
  codigo: "Código",
  grado: "Grado",
  nivel: "Nivel",
  naturaleza: "Naturaleza",
  situacionActual: "Situación Actual",
  novedad: "Novedad",
  salario2017: "Salario 2017",
  salario2018: "Primer Salario 2018",
  segundoIncremento: "Segundo incremento",
  salario2018Final: "Segundo Salario 2018",
  ipc318: "IPC 3.18%",
  salario2019: "Primer Salario 2019",
  salarioFinal2019: "Segundo Salario 2019",
  ipc380: "IPC 3.80%",
  salario2020: "Primer Salario 2020",
  salarioFinal2020: "Segundo Salario 2.5% 2020",
  salario2021: "Primer Salario 2021",
  salarioFinal2021: "Segundo Salario 4.0% 2021",
  salario2022: "Primer Salario 2022",
  salarioFinal2022: "Segundo Salario 2.0% 2022",
  opec: "OPEC",
  observacion: "Observación",
  pregrado: "Títulos de pregrado",
  especializacion: "Títulos de especializaciones",
  maestria: "Títulos de maestrías",
  doctorado: "Títulos de doctorados",
  eps: "EPS",
  pension: "Fondo de pensión",
  cesantias: "Fondo de cesantias",
  direccion: "Dirección",
  ciudad: "Ciudad",
  correoPersonal: "Correo personal",
  telefono: "Telefono Fijo",
  celular: "Celular",
  estadoCivil: "Estado Civil",
  hijos: "Hijos",
  otros: "Otros",
};
