export const labelText = {
  funcionarioLabel: "Funcionario",
  sexoLabel: "Sexo",
  correoLabel: "Correo Electrónico",
  cedulaLabel: "Cedula",
  expedidaLabel: "Expedida en:",
  fechaNacimientoLabel: "Fecha de nacimiento",
  lugarNacimientoLabel: "Lugar de nacimiento",
  fechaIngresoLabel: "Fecha Ingreso",
  tiempoServicioLabel: "Tiempo de servicio",
  dependenciaLabel: "Dependencia",
  areafuncionalLabel: "Área funcional",
  cargoLabel: "Cargo",
  codigoLabel: "Código",
  gradoLabel: "Grado",
  nivelLabel: "Nivel",
  naturalezaLabel: "Naturaleza",
  situacionActualLabel: "Situación Actual",
  novedadLabel: "Novedad",
  salario2017Label: "Salario 2017",
  salario2018Label: "Primer Salario 2018",
  segundoIncrementoLabel: "Segundo incremento",
  salario2018FinalLabel: "Segundo Salario 2018",
  ipc318Label: "IPC 3.18%",
  salario2019Label: "Primer Salario 2019",
  salarioFinal2019Label: "Segundo Salario 2019",
  ipc380Label: "IPC 3.80%",
  salario2020Label: "Primer Salario 2020",
  salarioFinal2020Label: "Segundo Salario 2.5% 2020",
  salario2021Label: "Primer Salario 2021",
  salarioFinal2021Label: "Segundo Salario 4.0% 2021",
  salario2022Label: "Primer Salario 2022",
  salarioFinal2022Label: "Segundo Salario 2.0% 2022",
  opecLabel: "OPEC",
  observacionLabel: "Observación",
  pregradoLabel: "Títulos de pregrado",
  especializacionLabel: "Títulos de especializaciones",
  maestriaLabel: "Títulos de maestrías",
  doctoradoLabel: "Títulos de doctorados",
  epsLabel: "EPS",
  pensionLabel: "Fondo de pensión",
  cesantiasLabel: "Fondo de cesantias",
  direccionLabel: "Dirección",
  ciudadLabel: "Ciudad",
  correoPersonalLabel: "Correo personal",
  telefonoLabel: "Telefono Fijo",
  celularLabel: "Celular",
  estadoCivilLabel: "Estado Civil",
  hijosLabel: "Hijos",
  otrosLabel: "Otros",
};
